"""init

Revision ID: 3f56c9f44e60
Revises:
Create Date: 2025-09-15 16:27:10.866669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f56c9f44e60"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imagemodels",
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("minio_object_name", sa.String(), nullable=False),
        sa.Column("compression_params", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("minio_object_name"),
    )
    op.create_index(op.f("ix_imagemodels_id"), "imagemodels", ["id"], unique=False)
    op.create_table(
        "usermodels",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usermodels_email"), "usermodels", ["email"], unique=True)
    op.create_index(op.f("ix_usermodels_id"), "usermodels", ["id"], unique=False)
    op.create_index(
        op.f("ix_usermodels_username"), "usermodels", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usermodels_username"), table_name="usermodels")
    op.drop_index(op.f("ix_usermodels_id"), table_name="usermodels")
    op.drop_index(op.f("ix_usermodels_email"), table_name="usermodels")
    op.drop_table("usermodels")
    op.drop_index(op.f("ix_imagemodels_id"), table_name="imagemodels")
    op.drop_table("imagemodels")
    # ### end Alembic commands ###
